theme: jekyll-theme-slate
title: Kazoo Install and Deploy Scripts
description: Collection of install scripts intended to be used on fresh CentOS 7 installations.
show_downloads: true
google_analytics: UA-102902171-9
